### ISSUE TITLE
Why not experiment on downstream tasks?

### ISSUE THREAD

**Issue by zhijiejia** [sail-sg/metaformer#1]
Excuse me, the network has achieved a good result, why not do experiments on downstream tasks to further verify the effectiveness of the network structure?

**Comment by yuweihao** [comment]
Hi @zhijiejia , thanks for your attention, since this paper induces 5 models (IdentityFormer, RandFormer, PoolFormerV2, ConvFormer, and CAFormer) at once and the computational resource is limited, we leave the experiment on downstream tasks in the future.
