### ISSUE TITLE
Any errors in finetuning scripts?

### ISSUE THREAD

**Issue by techmonsterwang** [sail-sg/metaformer#2]
Hi weihao, very interesting work.

I wonder whether there is a bug in scripts/caformer/finetune_384.sh?

The resolution should be 384×384, but in the scripts there are no relevant command line parameters indicating resolution such as --input-size or --img-size.

**Comment by yuweihao** [comment]
@techmonsterwang ,

Many thanks for your report! Another way is to change the model name to "XXX_384" like caformer_s18_384. I have fixed them in the scripts.
