### ISSUE TITLE
About downsampling(patch_embed) for first stage

### ISSUE THREAD

**Issue by DoranLyong** [sail-sg/metaformer#4]
Hi, thanks for your other interesting work after PoolFormer :) 

# Question1
I have some curiosity about setting the options for downsampling layers.
You seemed to comment `kernel_size:=4, stride:=4, and padding:=2`, but actually set as `[7,4,2]`. 
![image](https://user-images.githubusercontent.com/13333380/199390662-ee389ab1-6ac2-4c4b-969c-d0f9ff1e150b.png)

If the `kernel_size:=4`, stride and padding should be set as [4, 1]. 
But, do you run the experiments setting the kernel size as 7?

In your previous PoolFormer, the downsampling for the first stage is given [7, 4, 2] for kernel_size, stride, and padding.

***
# Question2
Another question: 
I have been reviewing the other Metaformer-like models (following 4-stage architecture) and I found there are many different options for making the same patch size for each stage; [56, 28, 14, 7]. 

For example, [Uniformer](https://github.com/Sense-X/UniFormer/blob/main/image_classification/models/uniformer.py) gives `kernel_size:=4` for the first stage and `kernel_size:=2` for remains.

In the downsampling stream, I wonder if you think there is some critical effect for their different kernel size?

**Comment by yuweihao** [comment]
Hi @DoranLyong ,

Many thanks for your attention.
Q1: It is a typo. The kernel size of the first downsampling is 7. I have fixed it.
Q2: From my experiments, `kernel_size:=7`for the first stage and `kernel_size:=3' for the remains perform better but bring more parameters and MACs. I used to reproduce ConvNeXt-Tiny (82.0%, 28.6M, 4.5G) vs ConvNeXt-Tiny-Downsampling-k7-k3 (82.3%, 30.5M, 4.7G).

**Comment by DoranLyong** [comment]
@yuweihao Thanks. That's a clear result :)

**Comment by yuweihao** [comment]
@DoranLyong ,

Since I have not conducted experiments in this config, sorry that I can not offer data points or give a summary. I remember MobileNetV2 also uses separable convolutions for downsampling.

![image](https://user-images.githubusercontent.com/15921929/199458651-68af13c8-efcb-42eb-b3fc-7220eea64ffd.png)

**Comment by DoranLyong** [comment]
@yuweihao  Great! was a good insight for me :)
