### ISSUE TITLE
Why use nn.Linear in SepConv?

### ISSUE THREAD

**Issue by iumyx2612** [sail-sg/metaformer#8]
![image](https://user-images.githubusercontent.com/69593462/215640788-eef34343-a2e5-4f40-8cee-788156bfec08.png)

Here we can simply use `nn.Conv2d` instead of `nn.Linear`, so that we don't have to use `permute` in the `forward` function. I'm sure authors are aware of this, why do authors chose to go with `nn.Linear`?

**Comment by yuweihao** [comment]
Hi @iumyx2612 , thanks for your attention. 

Dislike TensorFlow, PyTorch only supports [B, C, H, W] for nn.Conv2d. On the environment of PyTorch and GPU (A100), the implementation of [B, H, W, C] with `nn.Linear` is a little faster than [B,  C, H, W] with `nn.Conv2d`.

**Comment by iumyx2612** [comment]
> Hi @iumyx2612 , thanks for your attention.
> 
> Unlike TensorFlow, PyTorch only supports [B, C, H, W] for nn.Conv2d. On the environment of PyTorch and GPU (A100), the implementation of [B, H, W, C] with `nn.Linear` is a little faster than [B, C, H, W] with `nn.Conv2d`.

But using `nn.Linear` comes with a `permute` ops after. Is this (`nn.Linear` + `permute`) still faster than only `nn.Conv2d`?   
Btw really surprise that `nn.Linear` is faster than `nn.Conv2d`

**Comment by yuweihao** [comment]
Hi @iumyx2612 ,

Yes, on the environment of PyTorch and GPU, `nn.Linear + `permute` is a little faster than `nn.Conv2d`. This phenomenon is also shown in [ConvNext code](https://github.com/facebookresearch/ConvNeXt/blob/main/models/convnext.py#L15-L19).

**Comment by iumyx2612** [comment]
> Hi @iumyx2612 ,
> 
> Yes, on the environment of PyTorch and GPU, `LayerNorm` (channels_last) + `nn.Linear` + `permute` is a little faster than `LayerNorm` (channels_first) + `nn.Conv2d`. This phenomenon is also shown in [ConvNext code](https://github.com/facebookresearch/ConvNeXt/blob/main/models/convnext.py#L15-L19). I realized the speed may also be affected by the LayerNorm (channels_first or channels_list).
> 
> I only tested the whole model with the implementation of the above format. For the speed comparison of sorely `nn.Linear`/`nn.Linear` + `permute` and `nn.Conv2d`, I need to further verify it.

Thank you!

**Comment by yuweihao** [comment]
Hi @iumyx2612 ,

I test the operators by the following code and the results are shown.
```python
import torch
import torch.nn as nn
import time


class Permute(nn.Module):
    def __init__(self, *axis):
        super().__init__()
        self.axis = axis
    def forward(self, x):
        return x.permute(*self.axis)

        
B = 128
H = 28
W = 28
C = 384
num_warmup = 1000
num_run = 10000


implementations = {
    'bhwc_linear': {
        'format': [B, H, W, C],
        'model': nn.Linear(C, 4*C),
    },
    'bchw_permute_linear': {
        'format': [B, C, H, W],
        'model': nn.Sequential(
            Permute(0, 2, 3, 1), # [B, C, H, W] -> [B, H, W, C]
            nn.Linear(C, 4*C), 
            Permute(0, 3, 1, 2), # [B, C, H, W] -> [B, H, W, C]
        )
    },
    'bchw_conv2d': {
        'format': [B, C, H, W],
        'model': nn.Conv2d(C, 4*C, 1, 1)
    },
}

imp = 'bchw_conv2d'
model = implementations[imp]['model']
model = model.cuda()
format = implementations[imp]['format']

model.eval()
images = torch.rand(*format) - 0.5 
images = images.cuda(non_blocking=True)
with torch.no_grad():
    # warmup
    for i in range(num_warmup):
        model(images)
    print(f"throughput averaged with {num_run} times")
    torch.cuda.synchronize()
    tic1 = time.perf_counter()
    for i in range(num_run):
        model(images)
    torch.cuda.synchronize()
    tic2 = time.perf_counter()
    print(f"batch_size {B} throughput {num_run * B / (tic2 - tic1)}")


# throughput resutls on A100
# bhwc_linear: 61120.509191168974
# bchw_permute_linear: 50479.95421318548
# bchw_conv2d: 53265.63061490988
```

**Comment by iumyx2612** [comment]
> Hi @iumyx2612 ,
> 
> I test the operators by the following code and the results are shown.
> 
> ```python
> import torch
> import torch.nn as nn
> import time
> 
> 
> class Permute(nn.Module):
>     def __init__(self, *axis):
>         super().__init__()
>         self.axis = axis
>     def forward(self, x):
>         return x.permute(*self.axis)
> 
>         
> B = 128
> H = 28
> W = 28
> C = 384
> num_warmup = 1000
> num_run = 10000
> 
> 
> implementations = {
>     'bhwc_linear': {
>         'format': [B, H, W, C],
>         'model': nn.Linear(C, 4*C),
>     },
>     'bchw_permute_linear': {
>         'format': [B, C, H, W],
>         'model': nn.Sequential(
>             Permute(0, 2, 3, 1), # [B, C, H, W] -> [B, H, W, C]
>             nn.Linear(C, 4*C), 
>             Permute(0, 3, 1, 2), # [B, C, H, W] -> [B, H, W, C]
>         )
>     },
>     'bchw_conv2d': {
>         'format': [B, C, H, W],
>         'model': nn.Conv2d(C, 4*C, 1, 1)
>     },
> }
> 
> imp = 'bchw_conv2d'
> model = implementations[imp]['model']
> model = model.cuda()
> format = implementations[imp]['format']
> 
> model.eval()
> images = torch.rand(*format) - 0.5 
> images = images.cuda(non_blocking=True)
> with torch.no_grad():
>     # warmup
>     for i in range(num_warmup):
>         model(images)
>     print(f"throughput averaged with {num_run} times")
>     torch.cuda.synchronize()
>     tic1 = time.perf_counter()
>     for i in range(num_run):
>         model(images)
>     torch.cuda.synchronize()
>     tic2 = time.perf_counter()
>     print(f"batch_size {B} throughput {num_run * B / (tic2 - tic1)}")
> 
> 
> # throughput results on A100
> # bhwc_linear: 61120.509191168974
> # bchw_permute_linear: 50479.95421318548
> # bchw_conv2d: 53265.63061490988
> ```

it's funny using bhwc with linear is slower than bchw + permute + linear :question:

**Comment by yuweihao** [comment]
The followings are the new code and new results. 
```python
import torch
import torch.nn as nn
import time


class Permute(nn.Module):
    def __init__(self, *axis):
        super().__init__()
        self.axis = axis
    def forward(self, x):
        return x.permute(*self.axis)

        
B = 128
H = 28
W = 28
C = 384
M = 4 * C # hidden dim of MLP
num_warmup = 1000
num_run = 10000


implementations = {
    'bhwc_linear': {
        'format': [B, H, W, C],
        'model': nn.Sequential(
            nn.Linear(C, M),
            nn.ReLU(),
            nn.Linear(M, C),
        )
    },
    'bchw_permute_linear': {
        'format': [B, C, H, W],
        'model': nn.Sequential(
            Permute(0, 2, 3, 1), # [B, C, H, W] -> [B, H, W, C]
            nn.Linear(C, M), 
            nn.ReLU(),
            nn.Linear(M, C), 
            Permute(0, 3, 1, 2), # [B, H, W, C] -> [B, C, H, W]
        )
    },
    'bchw_conv2d': {
        'format': [B, C, H, W],
        'model': nn.Sequential(
            nn.Conv2d(C, M, 1, 1),
            nn.ReLU(),
            nn.Conv2d(M, C, 1, 1),
        )
    },
}

imp = 'bchw_conv2d'
model = implementations[imp]['model']
model = model.cuda()
format = implementations[imp]['format']

model.eval()
images = torch.rand(*format) - 0.5 
images = images.cuda(non_blocking=True)
with torch.no_grad():
    # warmup
    for i in range(num_warmup):
        model(images)
    print(f"throughput averaged with {num_run} times")
    torch.cuda.synchronize()
    tic1 = time.perf_counter()
    for i in range(num_run):
        model(images)
    torch.cuda.synchronize()
    tic2 = time.perf_counter()
    print(f"batch_size {B} throughput {num_run * B / (tic2 - tic1)}")


# throughput resutls on A100
# bhwc_linear: 29247.019901342566
# bchw_permute_linear: 26594.824167110604
# bchw_conv2d: 26578.51605369665
```

**Comment by yuweihao** [comment]
The throughput results vary at different runs. I further test  `permute` + 'linear`  and `conv2d` by more times, and find the throughput of them are almost the same.
