### ISSUE TITLE
can you give a more clear steps of training

### ISSUE THREAD

**Issue by Chaoran-F** [sail-sg/metaformer#9]
Hello, I am new to this field and I am very interested in your team's work, but the training process mentioned in your “readme”, I am very confused, I don't know where that part needs to be added for training, can you please Give me a more clear steps, thank you

**Comment by yuweihao** [comment]
Hi @Chaoran-F ,

Could I know about your environment? Have you prepared ImageNet? How many GPUs do you have?

Our code is based on the wonderful codebase [timm](https://github.com/rwightman/pytorch-image-models). You may also find more details from it.

**Comment by Chaoran-F** [comment]
> Hi @Chaoran-F ,
> 
> Could I know about your environment? Have you prepared ImageNet? How many GPUs do you have?
> 
> Our code is based on the wonderful codebase [timm](https://github.com/rwightman/pytorch-image-models). You may also find more details from it.

I am using cuda 11.4 with torch 1.10.2,timm 0.6.2, torchvision 0.11.2, and 4 gpus, and I already prepared imageNet(I tired swin-t before)

**Comment by yuweihao** [comment]
Hi @Chaoran-F ,

Great! Git clone this repo and run the following commands on your terminal,
```
DATA_PATH=/path/to/imagenet
CODE_PATH=/path/to/code/metaformer # modify code path here


ALL_BATCH_SIZE=4096
NUM_GPU=4
GRAD_ACCUM_STEPS=8 # Adjust according to your GPU numbers and memory size.
let BATCH_SIZE=ALL_BATCH_SIZE/NUM_GPU/GRAD_ACCUM_STEPS


cd $CODE_PATH && sh distributed_train.sh $NUM_GPU $DATA_PATH \
--model convformer_s18 --opt adamw --lr 4e-3 --warmup-epochs 20 \
-b $BATCH_SIZE --grad-accum-steps $GRAD_ACCUM_STEPS \
--drop-path 0.2 --head-dropout 0.0
```

**Comment by Chaoran-F** [comment]
> Hi @Chaoran-F ,
> 
> Great! Git clone this repo and run the following commands on your terminal,
> 
> ```
> DATA_PATH=/path/to/imagenet
> CODE_PATH=/path/to/code/metaformer # modify code path here
> 
> 
> ALL_BATCH_SIZE=4096
> NUM_GPU=4
> GRAD_ACCUM_STEPS=8 # Adjust according to your GPU numbers and memory size.
> let BATCH_SIZE=ALL_BATCH_SIZE/NUM_GPU/GRAD_ACCUM_STEPS
> 
> 
> cd $CODE_PATH && sh distributed_train.sh $NUM_GPU $DATA_PATH \
> --model convformer_s18 --opt adamw --lr 4e-3 --warmup-epochs 20 \
> -b $BATCH_SIZE --grad-accum-steps $GRAD_ACCUM_STEPS \
> --drop-path 0.2 --head-dropout 0.0
> ```

get it, thanks
